FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --default-timeout=200 --no-cache-dir -r requirements.txt

COPY . .

# 🔥 ADD THIS LINE
ENV PYTHONUNBUFFERED=1

CMD ["python", "worker.py"]